@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

HomeChef *-right-> "1" UniqueOrderList
HomeChef *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueOrderList
UniqueTagList -[hidden]down- UniqueOrderList

UniqueTagList -right-> "*" Tag
UniqueOrderList -right-> Order

Order -up-> "*" Tag

Order *--> Food
Order *--> Customer
Order *--> Phone
Order *--> Email
Order *--> Address
Order *--> Date
Order *--> Price
Order *--> PaymentType
Order *--> CompletionStatus
Order *--> PaymentStatus
@enduml
